swagger: '2.0'
info:
  version: '1'
  title: React demo eshop
  description: ''
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: 'Get all products success'
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductDto'
            default:
              items:
                name: 'Test 1'
                id: 1
                description: 'Lorem ipsum dolor sit amet'
  /orders:
    post:
      summary: Place an order
      parameters:
        - in: body
          name: order
          schema:
            $ref: '#/definitions/OrderDto'
      responses:
        '200':
          description: 'Order Created'
          schema:
            $ref: '#/definitions/OrderDto'

host: localhost:3333
schemes:
  - http
definitions:
  ProductDto:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
  ProductInBasketDto:
    type: object
    properties:
      product:
        $ref: '#/definitions/ProductDto'
      amount:
        type: integer
        format: int64
  OrderDto:
    type: object
    properties:
      id:
        type: integer
        format: int64
      items:
        type: array
        items:
          $ref: '#/definitions/ProductInBasketDto'
