swagger: '2.0'
info:
  version: '1'
  title: React demo eshop
  description: ''
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: 'Get all products success'
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'

# Added by API Auto Mocking Plugin
definitions:
  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
