swagger: '2.0'
info:
  version: '1'
  title: React demo eshop
  description: ''
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: 'Get all products success'
          schema:
            type: array
            items:
              $ref: '#/definitions/ProductDto'
            default:
              items:
                name: 'Test 1'
                id: 1
                description: 'Lorem ipsum dolor sit amet'

schemes:
  - https
definitions:
  ProductDto:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
